# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish Docker image

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ "master" ]
  workflow_dispatch:
  issues:
    types:
      - opened

jobs:
  push_to_registries:
    name: Push Docker image to github registry
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@master

      - name: Build image
        working-directory: docker/base
        run: |
          docker build -t distccd_gentoo .
